#!/bin/bash
http://netstorage.unity3d.com/unity/649f48bbbf0f/CacheServer-5.4.1f1.zip
VERSION="5.4.1f1"
CMD=/opt/CacheServer/RunLinux.sh

if [ ! -f $CMD ]
then
    echo "Download and unpack Unity Cache Server"
    cd /opt
    wget http://netstorage.unity3d.com/unity/649f48bbbf0f/CacheServer-${VERSION}.zip
    unzip CacheServer-${VERSION}.zip
    rm CacheServer-${VERSION}.zip
fi

echo "Starting Services"
/opt/CacheServer/RunLinux.sh
