#! /bin/sh
### BEGIN INIT INFO
# Provides:          unity_asset_cache_server
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts unity asset cache server
# Description:       starts unity asset cache server using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/opt/CacheServer/RunLinux.sh
DAEMON_LOG=/opt/CacheServer/unity_cache_server.log
NAME=unity-cache-server
PID_FILE=/var/tmp/$NAME.pid
DESC=unity-cache-server
DAEMON_OPTS=" "

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
        echo -n "Starting $DESC: "
        start-stop-daemon --start --quiet --make-pidfile --pidfile $PID_FILE \
                --background --exec /bin/bash -- -c "$DAEMON $DAEMON_ARGS > $DAEMON_LOG 2>1&"
        echo "$NAME."
        ;;
  stop)
        bashID=$(( $(cat $PID_FILE) + 1 ))
        echo -n "Stopping $DESC:"
        kill -9 $bashID
        rm $PID_FILE
        echo "$NAME. ($bashID)"
        ;;
  restart|force-reload)
        echo -n "Restarting $DESC: "
        bashID=$(( $(cat $PID_FILE) + 1 ))
        kill -9 $bashID
        rm $PID_FILE
        sleep 1
        start-stop-daemon --start --quiet --make-pidfile --pidfile $PID_FILE \
                --background --exec /bin/bash -- -c "$DAEMON $DAEMON_ARGS > $DAEMON_LOG 2>1&"
        echo "$NAME."
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
